 version: "3"

 services:

    rabbitmq:
        ports:
            - '5672:5672'
            - '15672:15672'
        image: 'rabbitmq:3.11-management'


    db:
        image: mariadb
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: 'changethispassword'

